version: "3.9"
services:
  workerdisk:
    build: .
    environment:
      - API_ID=${API_ID}
      - API_HASH=${HASH}
      - TOKEN=${TOKEN}
      - DB_NAME=${DB_NAME}
      - DB_URL=${DB_URL}
      - CHANNEL=${CHANNEL}
      - ADMIN=${ADMIN}
      - LAZY_PIC=${LAZY_PIC}
version: "3.3"

services:
  app:
    container_name: renamebot
    build: .
    command: python3 bot.py
    environment:
      API_ID: # Your API HASH from my.telegram.org
      API_HASH: # Your API ID from my.telegram.org
      TOKEN: # Bot token, get it from @BotFather 
      DB_NAME: # Pyrogram string session
      DB_URL: # User ID of Bot owner
      CHANNEL: # Username name of public channel without using '@'
      ADMIN:
      LAZY_PIC
